# List of plugins

set -g @continuum-restore 'on'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

setw -g mode-keys vi
bind ^C new-window -c "$HOME"

bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

bind r command-prompt -p "Rename window:" "rename-window '%%'"
bind H previous-window
bind L next-window
bind w list-windows
unbind |
bind s split-window -v -c "#{pane_current_path}"
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind C new-window -c "#{pane_current_path}"

bind g popup -E -w 90% -h 80% -d "#{pane_current_path}" "lazygit"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind p command-prompt -p "Rename pane:" "select-pane -T '%%'"

# Equalize pane sizes
bind = select-layout tiled           # Equalize all panes
bind | select-layout even-horizontal # Equal width (horizontal splits)
bind - select-layout even-vertical   # Equal height (vertical splits)

bind S display-popup -w 70% -h 60% -E "tmux list-sessions -F '#S' \
  | fzf \
  | xargs -I % tmux switch-client -t \"%\""

bind W new-session -c "~/projects"


black="#181a1f"
bg0="#282c34"
bg1="#31353f"
bg2="#393f4a"
bg3="#3b3f4c"
bg_d="#21252b"
bg_blue="#73b8f1"
bg_yellow="#ebd09c"
fg="#abb2bf"
purple="#c678dd"
green="#98c379"
orange="#d19a66"
blue="#61afef"
yellow="#e5c07b"
cyan="#56b6c2"
red="#e86671"
grey="#5c6370"
light_grey="#848b98"
dark_cyan="#2b6f77"
dark_red="#993939"
dark_yellow="#93691d"
dark_purple="#8a3fa0"

set -g status-position top
set -g status-left-length 220
set -g status-style "fg=${fg},bg=${black}"
set -g status-left "#[fg=${green},bold,bg=${bg2}] #S #[fg=${bg2},bg=${black}] "
set -g window-status-current-format "#[fg=${blue},bg=${black},bold] #[underscore]#I:#W "
set -g window-status-format "#[fg=${light_grey},bg=${black}] #I:#W "

set -g pane-border-status top
# set -g pane-border-format "#{pane_index} #T"
set -g pane-border-format '#{pane_index} #(pwd="#{pane_current_path}"; echo ${pwd####*/})'
set -g pane-active-border-style "fg=${cyan},bg=${black}"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run ~/.config/tmux/plugins/tpm/tpm
